//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.BL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sales.BL.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of the critical section on the file: {0}.
        /// </summary>
        internal static string BeginCriticalSection {
            get {
                return ResourceManager.GetString("BeginCriticalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending of the critical section on the file: {0}.
        /// </summary>
        internal static string EndCriticalSection {
            get {
                return ResourceManager.GetString("EndCriticalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} successfully moved.
        /// </summary>
        internal static string EndMoveFile {
            get {
                return ResourceManager.GetString("EndMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong in the next line: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file append: {0}.
        /// </summary>
        internal static string FileAppend {
            get {
                return ResourceManager.GetString("FileAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is successfully opened for reading.
        /// </summary>
        internal static string OpenRead {
            get {
                return ResourceManager.GetString("OpenRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To long path to folder for processed files.
        /// </summary>
        internal static string PathTooLongException {
            get {
                return ResourceManager.GetString("PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} reading is done. Prepare of writing to the database.
        /// </summary>
        internal static string ReadDone {
            get {
                return ResourceManager.GetString("ReadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to copy a file: {0}.
        /// </summary>
        internal static string StartMoveFile {
            get {
                return ResourceManager.GetString("StartMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystemWatcher is enabled.
        /// </summary>
        internal static string WatchDogStart {
            get {
                return ResourceManager.GetString("WatchDogStart", resourceCulture);
            }
        }
    }
}
